package fr.traqueur.victor.integration;

import fr.traqueur.victor.Victor;
import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.entities.Dto;
import fr.traqueur.victor.entities.Entity;
import fr.traqueur.victor.entities.Repository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class VictorDatabaseIntegrationTest {

    @AfterEach
    void cleanup() {
        try {
            var instance = Victor.getDefault();
            if (instance != null) {
                instance.close();
            }
        } catch (Exception ignored) {}
    }

    @Table(table = "test_users")
    static class TestUser implements Entity<Long> {
        @Id(autoGenerated = true)
        private Long id;

        @Column(nullable = false, unique = true, length = 50)
        private String username;

        @Column(nullable = false, length = 100)
        private String email;

        @Column(defaultValue = "true")
        private Boolean active = true;

        public TestUser() {}

        public TestUser(String username, String email) {
            this.username = username;
            this.email = email;
        }

        @Override
        public Long getId() { return id; }
        @Override
        public void setId(Long id) { this.id = id; }

        public String getUsername() { return username; }
        public void setUsername(String username) { this.username = username; }

        public String getEmail() { return email; }
        public void setEmail(String email) { this.email = email; }

        public Boolean getActive() { return active; }
        public void setActive(Boolean active) { this.active = active; }

        @Override
        public String toString() {
            return "TestUser{id=" + id + ", username='" + username + "', email='" + email + "', active=" + active + "}";
        }
    }

    record TestUserDto(Long id, String username, String email, Boolean active) implements Dto<TestUser> {

        public static TestUserDto create(String username, String email) {
            return new TestUserDto(null, username, email, true);
        }

        @Override
        public TestUser toModel() {
            var user = new TestUser();
            user.setId(id);
            user.setUsername(username);
            user.setEmail(email);
            user.setActive(active);
            return user;
        }
    }

    interface TestUserRepository extends Repository<TestUserDto, TestUser, Long> {}

    @BeforeEach
    void setup() {
        // Utiliser une base différente pour chaque test
        String dbName = "test_db_" + System.nanoTime();

        // Configure Victor avec auto-migration et entités
        var victor = Victor.configure()
                .h2()
                .database(dbName)
                .showSql()
                .autoMigrate()
                .autoScanEntities("fr.traqueur.victor.integration")  // Scan seulement le package de test
                .build();

        // Set as default
        Victor.setDefault(victor);

        // Force migration run
        victor.runMigrations();
    }

    @Test
    void testTableCreation() {
        System.out.println("=== Testing Table Creation ===");

        // Auto-migration should have created the table
        assertDoesNotThrow(() -> {
            TestUserRepository repo = Victor.withRepository(TestUserRepository.class);
            assertNotNull(repo);

            // Table should exist and be queryable
            long count = repo.count();
            assertEquals(0L, count);

            System.out.println("✓ Table created and accessible");
        });
    }

    @Test
    void testCrudOperations() {
        System.out.println("=== Testing CRUD Operations ===");

        TestUserRepository repo = Victor.withRepository(TestUserRepository.class);

        // CREATE
        TestUserDto newUser = TestUserDto.create("johndoe", "john@example.com");
        TestUserDto savedUser = repo.save(newUser);

        assertNotNull(savedUser);
        assertNotNull(savedUser.id());
        assertEquals("johndoe", savedUser.username());
        assertEquals("john@example.com", savedUser.email());
        assertTrue(savedUser.active());

        System.out.println("✓ Create: " + savedUser);

        // READ
        Optional<TestUserDto> foundUser = repo.findById(savedUser.id());
        assertTrue(foundUser.isPresent());
        assertEquals(savedUser.username(), foundUser.get().username());

        System.out.println("✓ Read: " + foundUser.get());

        // UPDATE
        TestUserDto updatedUser = new TestUserDto(savedUser.id(), "johnsmith", "johnsmith@example.com", false);
        TestUserDto resultUser = repo.save(updatedUser);

        assertEquals("johnsmith", resultUser.username());
        assertEquals("johnsmith@example.com", resultUser.email());
        assertFalse(resultUser.active());

        System.out.println("✓ Update: " + resultUser);

        // DELETE
        repo.deleteById(savedUser.id());

        Optional<TestUserDto> deletedUser = repo.findById(savedUser.id());
        assertFalse(deletedUser.isPresent());

        System.out.println("✓ Delete: User removed");
    }

    @Test
    void testBulkOperations() {
        System.out.println("=== Testing Bulk Operations ===");

        TestUserRepository repo = Victor.withRepository(TestUserRepository.class);

        // Create multiple users
        var users = java.util.List.of(
                TestUserDto.create("alice", "alice@example.com"),
                TestUserDto.create("bob", "bob@example.com"),
                TestUserDto.create("charlie", "charlie@example.com")
        );

        var savedUsers = repo.saveAll(users);
        assertEquals(3, savedUsers.size());

        System.out.println("✓ Bulk create: " + savedUsers.size() + " users");

        // Find all
        var allUsers = repo.findAll();
        assertEquals(3, allUsers.size());

        System.out.println("✓ Find all: " + allUsers.size() + " users");

        // Count
        long count = repo.count();
        assertEquals(3L, count);

        System.out.println("✓ Count: " + count);

        // Delete all
        repo.deleteAll();

        count = repo.count();
        assertEquals(0L, count);

        System.out.println("✓ Delete all: " + count + " remaining");
    }

    @Test
    void testQueryBuilder() {
        System.out.println("=== Testing Query Builder ===");

        TestUserRepository repo = Victor.withRepository(TestUserRepository.class);

        // Create test data
        repo.save(TestUserDto.create("alice", "alice@company.com"));
        repo.save(TestUserDto.create("bob", "bob@company.com"));
        repo.save(TestUserDto.create("charlie", "charlie@external.com"));

        // Test query builder
        var companyUsers = repo.query()
                .where("email LIKE ?", "%@company.com")
                .orderByAsc("username")
                .findAll();

        assertEquals(2, companyUsers.size());
        assertEquals("alice", companyUsers.get(0).username());
        assertEquals("bob", companyUsers.get(1).username());

        System.out.println("✓ Query builder: " + companyUsers.size() + " company users");

        // Test count query
        long companyCount = repo.query()
                .where("email LIKE ?", "%@company.com")
                .count();

        assertEquals(2L, companyCount);

        System.out.println("✓ Query count: " + companyCount);

        // Test exists
        boolean hasExternal = repo.query()
                .where("email LIKE ?", "%@external.com")
                .exists();

        assertTrue(hasExternal);

        System.out.println("✓ Query exists: " + hasExternal);
    }
}