package fr.traqueur.victor.entity.dialect.h2;

import fr.traqueur.victor.entity.dialect.Dialect;
import fr.traqueur.victor.entity.metadata.EntityMetadata;
import fr.traqueur.victor.entity.metadata.FieldMetadata;

import java.util.Properties;
import java.util.stream.Collectors;

public class H2Dialect implements Dialect {

    @Override
    public String getName() {
        return "h2";
    }

    @Override
    public String getDriverClassName() {
        return "org.h2.Driver";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:h2:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        if (host != null && port > 0) {
            return String.format("jdbc:h2:tcp://%s:%d/%s", host, port, database);
        } else {
            if (database.startsWith("mem:") || database.startsWith("file:")) {
                return "jdbc:h2:" + database;
            } else {
                return "jdbc:h2:mem:" + database;
            }
        }
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        Properties props = new Properties();
        props.setProperty("DB_CLOSE_ON_EXIT", "FALSE");
        props.setProperty("DB_CLOSE_DELAY", "-1");
        props.setProperty("MODE", "MySQL");
        return props;
    }

    @Override
    public String generateCreateTable(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");

        if (metadata.getSchema() != null) {
            sql.append(quoteIdentifier(metadata.getSchema())).append(".");
        }

        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");

        var columnDefinitions = metadata.getFields().stream()
            .map(this::generateColumnDefinition)
            .collect(Collectors.toList());

        sql.append("  ").append(String.join(",\n  ", columnDefinitions));

        sql.append(",\n  PRIMARY KEY (").append(quoteIdentifier(metadata.getIdField().getColumnName())).append(")");

        var uniqueFields = metadata.getFields().stream()
            .filter(f -> f.isUnique() && !f.isId())
            .toList();

        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE (").append(quoteIdentifier(field.getColumnName())).append(")");
        }

        sql.append("\n)");

        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");

        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType(), field));
        }

        if (field.isId() && field.isAutoGenerated()) {
            def.append(" AUTO_INCREMENT");
        }

        if (!field.isNullable()) {
            def.append(" NOT NULL");
        }

        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(field.getDefaultValue()).append("'");
            } else {
                def.append(field.getDefaultValue());
            }
        }

        return def.toString();
    }

    @Override
    public String generateUpsert(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("MERGE INTO ").append(getFullTableName(metadata));

        var allFields = metadata.getFields();
        String columns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String placeholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        sql.append(" (").append(columns).append(")")
                .append(" KEY(").append(quoteIdentifier(metadata.getIdField().getColumnName())).append(")")
                .append(" VALUES (").append(placeholders).append(")");

        return sql.toString();
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class || javaType.isEnum()) {
            int length = fieldMetadata != null ? fieldMetadata.getLength() : 255;
            return "VARCHAR(" + length + ")";
        } else if (javaType == Long.class || javaType == long.class) {
            return "BIGINT";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INTEGER";
        } else if (javaType == Short.class || javaType == short.class) {
            return "SMALLINT";
        } else if (javaType == Byte.class || javaType == byte.class) {
            return "TINYINT";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "BOOLEAN";
        } else if (javaType == Double.class || javaType == double.class) {
            return "DOUBLE";
        } else if (javaType == Float.class || javaType == float.class) {
            return "REAL";
        } else if (javaType == java.math.BigDecimal.class) {
            return "DECIMAL(19, 2)";
        } else if (javaType == java.time.LocalDateTime.class) {
            return "TIMESTAMP";
        } else if (javaType == java.time.LocalDate.class) {
            return "DATE";
        } else if (javaType == java.time.LocalTime.class) {
            return "TIME";
        } else if (javaType == byte[].class) {
            return "BLOB";
        } else if (javaType == java.util.UUID.class) {
            return "UUID";
        } else {
            return "CLOB";
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier + "\"";
    }

    @Override
    public boolean supportsSchemas() {
        return true;
    }

    @Override
    public boolean supportsJsonType() {
        return false;
    }

    @Override
    public boolean isEmbedded() {
        return true;
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        return "AUTO_INCREMENT";
    }

    @Override
    public String generateListTablesSQL(String schemaName) {
        // H2 2.x uses TABLE_TYPE = 'BASE TABLE' for user tables in PUBLIC schema.
        // We filter by TABLE_SCHEMA to avoid returning INFORMATION_SCHEMA system tables.
        String schema = schemaName != null ? schemaName.toUpperCase() : "PUBLIC";
        return String.format(
                "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '%s' AND TABLE_TYPE = 'BASE TABLE'",
                schema
        );
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
            "SET MODE MySQL",
            "SET DB_CLOSE_DELAY -1"
        };
    }

    @Override
    public String generateListColumnsSQL(String tableName, String schemaName) {
        if (schemaName != null) {
            return String.format(
                    "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT " +
                    "FROM INFORMATION_SCHEMA.COLUMNS " +
                    "WHERE TABLE_NAME = '%s' AND TABLE_SCHEMA = '%s'",
                    tableName.toUpperCase(), schemaName.toUpperCase()
            );
        }
        return String.format(
                "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT " +
                "FROM INFORMATION_SCHEMA.COLUMNS " +
                "WHERE TABLE_NAME = '%s'",
                tableName.toUpperCase()
        );
    }

    @Override
    public String generateAddColumn(EntityMetadata metadata, FieldMetadata field) {
        StringBuilder sql = new StringBuilder();
        sql.append("ALTER TABLE ").append(getFullTableName(metadata));
        sql.append(" ADD COLUMN ");
        sql.append(quoteIdentifier(field.getColumnName())).append(" ");
        if (field.hasCustomSqlType()) {
            sql.append(field.getSqlType());
        } else {
            sql.append(mapJavaTypeToSql(field.getJavaType(), field));
        }
        if (!field.isNullable()) {
            sql.append(" NOT NULL");
        }
        if (field.hasDefaultValue()) {
            sql.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                sql.append("'").append(field.getDefaultValue()).append("'");
            } else {
                sql.append(field.getDefaultValue());
            }
        }
        return sql.toString();
    }
}