package fr.traqueur.victor.entities.dialect.sqlite;

import fr.traqueur.victor.entities.dialect.Dialect;
import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;

import java.util.Properties;
import java.util.stream.Collectors;

public class SQLiteDialect implements Dialect {
    @Override
    public String getName() {
        return "sqlite";
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
                "PRAGMA foreign_keys = ON",
                "PRAGMA journal_mode = WAL"
        };
    }

    @Override
    public String getDriverClassName() {
        return "org.sqlite.JDBC";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:sqlite:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        if (database.equals(":memory:")) {
            return "jdbc:sqlite::memory:";
        }

        if (database.startsWith("jdbc:sqlite:")) {
            return database;
        }

        return "jdbc:sqlite:" + database;
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        return new Properties();
    }

    @Override
    public String generateCreateTable(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");

        // ⚠️ SQLite ne supporte PAS les schémas, ignorer metadata.getSchema()
        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");

        // Colonnes
        var columnDefinitions = metadata.getFields().stream()
                .map(this::generateColumnDefinition)
                .collect(Collectors.toList());

        sql.append("  ").append(String.join(",\n  ", columnDefinitions));

        // Primary key
        sql.append(",\n  PRIMARY KEY (")
                .append(quoteIdentifier(metadata.getIdField().getColumnName()))
                .append(")");

        // Unique constraints
        var uniqueFields = metadata.getFields().stream()
                .filter(f -> f.isUnique() && !f.isId())
                .toList();

        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE (")
                    .append(quoteIdentifier(field.getColumnName()))
                    .append(")");
        }

        sql.append("\n)");

        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");

        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType(), field));
        }

        if (field.isId() && field.isAutoGenerated()) {
            def.append(" AUTOINCREMENT");
        }

        // NOT NULL
        if (!field.isNullable()) {
            def.append(" NOT NULL");
        }

        // Default value
        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(field.getDefaultValue()).append("'");
            } else {
                def.append(field.getDefaultValue());
            }
        }

        return def.toString();
    }

    @Override
    public String generateInsert(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String columns = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String placeholders = nonIdFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        return String.format("INSERT INTO %s (%s) VALUES (%s)",
                getFullTableName(metadata), columns, placeholders);
    }

    @Override
    public String generateUpdate(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String setClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = ?")
                .collect(Collectors.joining(", "));

        return String.format("UPDATE %s SET %s WHERE %s = ?",
                getFullTableName(metadata), setClause, quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateUpsert(EntityMetadata metadata) {
        var allFields = metadata.getFields();
        var nonIdFields = metadata.getNonIdFields();

        String insertColumns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String insertPlaceholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        String updateSetClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = excluded." + quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        return String.format(
                "INSERT INTO %s (%s) VALUES (%s) ON CONFLICT(%s) DO UPDATE SET %s",
                getFullTableName(metadata),
                insertColumns,
                insertPlaceholders,
                quoteIdentifier(metadata.getIdField().getColumnName()),
                updateSetClause
        );
    }

    @Override
    public String generateDelete(EntityMetadata metadata) {
        return String.format("DELETE FROM %s WHERE %s = ?",
                getFullTableName(metadata), quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateSelectById(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s WHERE %s = ?",
                getFullTableName(metadata), quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateSelectAll(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s", getFullTableName(metadata));
    }

    @Override
    public String generateCount(EntityMetadata metadata) {
        return String.format("SELECT COUNT(*) FROM %s", getFullTableName(metadata));
    }

    @Override
    public String generateExists(EntityMetadata metadata) {
        return String.format("SELECT 1 FROM %s WHERE %s = ? LIMIT 1",
                getFullTableName(metadata), quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class) {
            return "TEXT";
        } else if (javaType == Long.class || javaType == long.class) {
            return "INTEGER";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INTEGER";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "INTEGER";
        } else if (javaType == Double.class || javaType == double.class) {
            return "REAL";
        } else if (javaType == Float.class || javaType == float.class) {
            return "REAL";
        } else if (javaType == java.time.LocalDateTime.class) {
            return "TEXT";
        } else if (javaType == byte[].class) {
            return "BLOB";
        } else {
            return "TEXT";
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier + "\"";
    }

    @Override
    public String escapeLikePattern(String pattern) {
        return pattern.replace("\\", "\\\\")
                .replace("%", "\\%")
                .replace("_", "\\_");
    }

    @Override
    public boolean supportsSchemas() {
        return false;
    }

    @Override
    public boolean supportsSequences() {
        return false;
    }

    @Override
    public boolean supportsJsonType() {
        return true;
    }

    @Override
    public boolean isEmbedded() {
        return true;
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        return "AUTOINCREMENT";
    }
    private String getFullTableName(EntityMetadata metadata) {
        return quoteIdentifier(metadata.getTableName());
    }
}
