package fr.traqueur.victor.entities.dialect.sqlite;

import fr.traqueur.victor.entities.dialect.Dialect;
import fr.traqueur.victor.entities.metadata.DtoMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;

import java.util.Properties;
import java.util.stream.Collectors;

public class SQLiteDialect implements Dialect {

    @Override
    public String getName() {
        return "sqlite";
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
                "PRAGMA foreign_keys = ON",
                "PRAGMA journal_mode = WAL"
        };
    }

    @Override
    public String getDriverClassName() {
        return "org.sqlite.JDBC";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:sqlite:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        StringBuilder url = new StringBuilder();

        if (database.equals(":memory:")) {
            url.append("jdbc:sqlite:file:memdb1?mode=memory&cache=shared");
        } else if (database.startsWith("jdbc:sqlite:")) {
            return database;
        } else {
            url.append("jdbc:sqlite:").append(database);
        }

        if (!properties.isEmpty()) {
            if (!url.toString().contains("?")) {
                url.append("?");
            } else {
                url.append("&");
            }
            properties.forEach((key, value) -> {
                url.append(key).append("=").append(value).append("&");
            });
            url.setLength(url.length() - 1);
        }

        return url.toString();
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        return new Properties();
    }

    @Override
    public String generateCreateTable(DtoMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");

        // SQLite does not support schemas
        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");

        var columnDefinitions = metadata.getFields().stream()
                .map(this::generateColumnDefinition)
                .collect(Collectors.toList());

        sql.append("  ").append(String.join(",\n  ", columnDefinitions));

        if (!metadata.getIdField().isAutoGenerated()) {
            sql.append(",\n  PRIMARY KEY (")
                    .append(quoteIdentifier(metadata.getIdField().getColumnName()))
                    .append(")");
        }

        var uniqueFields = metadata.getFields().stream()
                .filter(f -> f.isUnique() && !f.isId())
                .toList();

        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE (")
                    .append(quoteIdentifier(field.getColumnName()))
                    .append(")");
        }

        sql.append("\n)");

        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");

        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType(), field));
        }

        // SQLite: AUTOINCREMENT must be combined with PRIMARY KEY inline
        if (field.isId() && field.isAutoGenerated()) {
            def.append(" PRIMARY KEY AUTOINCREMENT");
        }

        if (!field.isNullable() && !field.isId()) {
            def.append(" NOT NULL");
        }

        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(field.getDefaultValue()).append("'");
            } else {
                def.append(field.getDefaultValue());
            }
        }

        return def.toString();
    }

    @Override
    public String generateUpsert(DtoMetadata metadata) {
        var allFields = metadata.getFields();
        var nonIdFields = metadata.getNonIdFields();

        String insertColumns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String insertPlaceholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        String updateSetClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = excluded." + quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        return String.format(
                "INSERT INTO %s (%s) VALUES (%s) ON CONFLICT(%s) DO UPDATE SET %s",
                getFullTableName(metadata),
                insertColumns,
                insertPlaceholders,
                quoteIdentifier(metadata.getIdField().getColumnName()),
                updateSetClause
        );
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class) {
            return "TEXT";
        } else if (javaType == Long.class || javaType == long.class) {
            return "INTEGER";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INTEGER";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "INTEGER";
        } else if (javaType == Double.class || javaType == double.class) {
            return "REAL";
        } else if (javaType == Float.class || javaType == float.class) {
            return "REAL";
        } else if (javaType == java.time.LocalDateTime.class) {
            return "TEXT";
        } else if (javaType == byte[].class) {
            return "BLOB";
        } else if (javaType == java.util.UUID.class) {
            return "TEXT";
        } else {
            return "TEXT";
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier + "\"";
    }

    @Override
    public boolean supportsSchemas() {
        return false;
    }

    @Override
    public boolean supportsSequences() {
        return false;
    }

    @Override
    public boolean supportsJsonType() {
        return true;
    }

    @Override
    public boolean isEmbedded() {
        return true;
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        return "AUTOINCREMENT";
    }

    @Override
    public String generateListTablesSQL(String schemaName) {
        return "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'";
    }

    @Override
    public boolean supportsStandardGeneratedKeys() {
        return false;
    }

    @Override
    public String getLastInsertIdSql() {
        return "SELECT last_insert_rowid()";
    }

    @Override
    public String generateListColumnsSQL(String tableName, String schemaName) {
        return "PRAGMA table_info(" + quoteIdentifier(tableName) + ")";
    }

    @Override
    public String generateAddColumn(DtoMetadata metadata, FieldMetadata field) {
        StringBuilder sql = new StringBuilder();
        sql.append("ALTER TABLE ").append(quoteIdentifier(metadata.getTableName()));
        sql.append(" ADD COLUMN ");
        sql.append(quoteIdentifier(field.getColumnName())).append(" ");
        if (field.hasCustomSqlType()) {
            sql.append(field.getSqlType());
        } else {
            sql.append(mapJavaTypeToSql(field.getJavaType(), field));
        }
        // SQLite: NOT NULL requires a default value
        if (!field.isNullable() && field.hasDefaultValue()) {
            sql.append(" NOT NULL");
        }
        if (field.hasDefaultValue()) {
            sql.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                sql.append("'").append(field.getDefaultValue()).append("'");
            } else {
                sql.append(field.getDefaultValue());
            }
        }
        return sql.toString();
    }

    /**
     * SQLite does not support ADD FOREIGN KEY via ALTER TABLE.
     * FK constraints must be defined at CREATE TABLE time.
     */
    @Override
    public String generateAddForeignKeyConstraint(String tableName, String fkColumn,
                                                  String referencedTable, String referencedColumn) {
        return null;
    }

    @Override
    public boolean supportsPartialIndexes() {
        return true;
    }
}