package fr.traqueur.victor.entities.metadata;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.exceptions.VictorException;
import fr.traqueur.victor.utils.StringUtils;

import java.lang.reflect.Field;

public final class FieldMetadata {
    
    private final Field field;
    private final String columnName;
    private final Class<?> javaType;
    private final boolean nullable;
    private final int length;
    private final boolean unique;
    private final String defaultValue;
    private final String sqlType;
    private final boolean isId;
    private final boolean autoGenerated;
    private final String sequence;
    
    private FieldMetadata(Field field) {
        this.field = field;
        this.field.setAccessible(true);
        this.javaType = field.getType();
        
        var column = field.getAnnotation(Column.class);
        this.columnName = (column != null && !column.name().isEmpty()) ? 
            column.name() : StringUtils.camelToSnakeCase(field.getName());
        
        this.nullable = column == null || column.nullable();
        this.length = column != null ? column.length() : 255;
        this.unique = column != null && column.unique();
        this.defaultValue = column != null ? column.defaultValue() : "";
        this.sqlType = column != null ? column.sqlType() : "";
        
        this.isId = field.isAnnotationPresent(Id.class);
        
        if (isId) {
            var id = field.getAnnotation(Id.class);
            this.autoGenerated = id.autoGenerated();
            this.sequence = id.sequence().isEmpty() ? null : id.sequence();
        } else {
            this.autoGenerated = false;
            this.sequence = null;
        }
    }
    
    public static FieldMetadata of(Field field) {
        return new FieldMetadata(field);
    }
    
    public Object getValue(Object entity) {
        try {
            return field.get(entity);
        } catch (IllegalAccessException e) {
            throw new VictorException("Failed to get value from field: " + field, e);
        }
    }
    
    public void setValue(Object entity, Object value) {
        try {
            field.set(entity, value);
        } catch (IllegalAccessException e) {
            throw new VictorException("Failed to set value to field: " + field, e);
        }
    }
    
    public Field getField() { return field; }
    public String getColumnName() { return columnName; }
    public Class<?> getJavaType() { return javaType; }
    public boolean isNullable() { return nullable; }
    public int getLength() { return length; }
    public boolean isUnique() { return unique; }
    public String getDefaultValue() { return defaultValue; }
    public String getSqlType() { return sqlType; }
    public boolean isId() { return isId; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public String getSequence() { return sequence; }
    
    public boolean hasCustomSqlType() {
        return !sqlType.isEmpty();
    }
    
    public boolean hasDefaultValue() {
        return !defaultValue.isEmpty();
    }
}