package fr.traqueur.victor.database;

import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;
import fr.traqueur.victor.types.VictorDialect;

import java.util.List;
import java.util.stream.Collectors;

public final class SqlGenerator {
    
    private final VictorDialect dialect;
    
    public SqlGenerator(VictorDialect dialect) {
        this.dialect = dialect;
    }
    
    // ========== CREATE TABLE ==========
    
    public String generateCreateTable(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");
        
        if (metadata.getSchema() != null && dialect.supportsSchemas()) {
            sql.append(metadata.getSchema()).append(".");
        }
        
        sql.append(metadata.getTableName()).append(" (\n");
        
        // Add columns
        List<String> columnDefinitions = metadata.getFields().stream()
            .map(this::generateColumnDefinition)
            .collect(Collectors.toList());
        
        sql.append("  ").append(String.join(",\n  ", columnDefinitions));
        
        // Add primary key constraint
        sql.append(",\n  PRIMARY KEY (").append(metadata.getIdField().getColumnName()).append(")");
        
        // Add unique constraints
        var uniqueFields = metadata.getFields().stream()
            .filter(f -> f.isUnique() && !f.isId())
            .toList();
        
        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE (").append(field.getColumnName()).append(")");
        }
        
        sql.append("\n)");
        
        // Add table options based on dialect
        switch (dialect) {
            case MYSQL, MARIADB -> sql.append(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            case POSTGRESQL -> {
                // PostgreSQL doesn't need additional options
            }
            case SQLITE -> {
                // SQLite doesn't need additional options
            }
            case H2 -> {
                // H2 doesn't need additional options
            }
        }
        
        return sql.toString();
    }
    
    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(field.getColumnName()).append(" ");
        
        // Use custom SQL type if specified
        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType()));
        }
        
        // Add AUTO_INCREMENT for ID fields
        if (field.isId() && field.isAutoGenerated()) {
            switch (dialect) {
                case MYSQL, MARIADB, H2 -> def.append(" AUTO_INCREMENT");
                case POSTGRESQL -> {
                    // PostgreSQL uses SERIAL or IDENTITY
                    if (field.getJavaType() == Long.class || field.getJavaType() == long.class) {
                        def = new StringBuilder(field.getColumnName() + " BIGSERIAL");
                    } else {
                        def = new StringBuilder(field.getColumnName() + " SERIAL");
                    }
                }
                case SQLITE -> {
                    // SQLite uses INTEGER PRIMARY KEY for auto-increment
                    if (field.getJavaType() == Long.class || field.getJavaType() == long.class ||
                        field.getJavaType() == Integer.class || field.getJavaType() == int.class) {
                        def = new StringBuilder(field.getColumnName() + " INTEGER");
                    }
                }
            }
        }
        
        // Add NOT NULL constraint
        if (!field.isNullable()) {
            def.append(" NOT NULL");
        }
        
        // Add DEFAULT value
        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            String defaultValue = field.getDefaultValue();
            
            // Quote string defaults
            if (field.getJavaType() == String.class && !defaultValue.startsWith("'")) {
                def.append("'").append(defaultValue).append("'");
            } else {
                def.append(defaultValue);
            }
        }
        
        return def.toString();
    }
    
    private String mapJavaTypeToSql(Class<?> javaType) {
        if (javaType == String.class) {
            return switch (dialect) {
                case MYSQL, MARIADB, POSTGRESQL -> "VARCHAR(255)";
                case SQLITE -> "TEXT";
                case H2 -> "VARCHAR(255)";
            };
        } else if (javaType == Long.class || javaType == long.class) {
            return switch (dialect) {
                case MYSQL, MARIADB, H2 -> "BIGINT";
                case POSTGRESQL -> "BIGINT";
                case SQLITE -> "INTEGER";
            };
        } else if (javaType == Integer.class || javaType == int.class) {
            return switch (dialect) {
                case MYSQL, MARIADB -> "INT";
                case POSTGRESQL, SQLITE, H2 -> "INTEGER";
            };
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return switch (dialect) {
                case MYSQL, MARIADB, POSTGRESQL, H2 -> "BOOLEAN";
                case SQLITE -> "INTEGER"; // SQLite doesn't have boolean
            };
        } else if (javaType == Double.class || javaType == double.class) {
            return switch (dialect) {
                case MYSQL, MARIADB, H2 -> "DOUBLE";
                case POSTGRESQL -> "DOUBLE PRECISION";
                case SQLITE -> "REAL";
            };
        } else if (javaType == Float.class || javaType == float.class) {
            return switch (dialect) {
                case MYSQL, MARIADB -> "FLOAT";
                case POSTGRESQL, SQLITE, H2 -> "REAL";
            };
        } else if (javaType == java.time.LocalDateTime.class) {
            return switch (dialect) {
                case MYSQL, MARIADB -> "DATETIME";
                case POSTGRESQL, H2 -> "TIMESTAMP";
                case SQLITE -> "TEXT"; // SQLite stores as ISO string
            };
        } else {
            // Fallback for unknown types
            return "TEXT";
        }
    }
    
    // ========== CRUD Operations ==========
    
    public String generateInsert(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String columns = nonIdFields.stream()
            .map(FieldMetadata::getColumnName)
            .collect(Collectors.joining(", "));
        
        String placeholders = nonIdFields.stream()
            .map(f -> "?")
            .collect(Collectors.joining(", "));
        
        return String.format("INSERT INTO %s (%s) VALUES (%s)",
            metadata.getFullTableName(), columns, placeholders);
    }
    
    public String generateUpdate(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String setClause = nonIdFields.stream()
            .map(f -> f.getColumnName() + " = ?")
            .collect(Collectors.joining(", "));
        
        return String.format("UPDATE %s SET %s WHERE %s = ?",
            metadata.getFullTableName(), setClause, metadata.getIdField().getColumnName());
    }
    
    public String generateDelete(EntityMetadata metadata) {
        return String.format("DELETE FROM %s WHERE %s = ?",
            metadata.getFullTableName(), metadata.getIdField().getColumnName());
    }
    
    public String generateSelectById(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s WHERE %s = ?",
            metadata.getFullTableName(), metadata.getIdField().getColumnName());
    }
    
    public String generateSelectAll(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s", metadata.getFullTableName());
    }
    
    public String generateCount(EntityMetadata metadata) {
        return String.format("SELECT COUNT(*) FROM %s", metadata.getFullTableName());
    }
    
    public String generateExists(EntityMetadata metadata) {
        return String.format("SELECT 1 FROM %s WHERE %s = ? LIMIT 1",
            metadata.getFullTableName(), metadata.getIdField().getColumnName());
    }
    
    // ========== Utility ==========
    
    public String quoteIdentifier(String identifier) {
        return switch (dialect) {
            case MYSQL, MARIADB -> "`" + identifier + "`";
            case POSTGRESQL, SQLITE, H2 -> "\"" + identifier + "\"";
        };
    }
    
    public String escapeLikePattern(String pattern) {
        return pattern.replace("\\", "\\\\")
                     .replace("%", "\\%")
                     .replace("_", "\\_");
    }
}