package fr.traqueur.victor.entities.dialect.mysql;

import fr.traqueur.victor.database.migration.IndexDefinition;
import fr.traqueur.victor.entities.dialect.Dialect;
import fr.traqueur.victor.entities.metadata.DtoMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Properties;
import java.util.UUID;
import java.util.stream.Collectors;

public class MySQLDialect implements Dialect {

    @Override
    public String getName() {
        return "mysql";
    }

    @Override
    public String getDriverClassName() {
        return "com.mysql.cj.jdbc.Driver";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:mysql:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        if (port == 0) {
            port = 3306;
        }
        StringBuilder url = new StringBuilder();
        url.append("jdbc:mysql://")
                .append(host)
                .append(":")
                .append(port)
                .append("/")
                .append(database);

        if (!properties.isEmpty()) {
            url.append("?");
            properties.forEach((key, value) -> {
                url.append(key).append("=").append(value).append("&");
            });
            url.setLength(url.length() - 1);
        }

        return url.toString();
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        Properties props = new Properties();
        props.setProperty("characterEncoding", "UTF-8");
        props.setProperty("useUnicode", "true");
        props.setProperty("serverTimezone", "UTC");
        props.setProperty("cachePrepStmts", "true");
        props.setProperty("prepStmtCacheSize", "250");
        props.setProperty("prepStmtCacheSqlLimit", "2048");
        props.setProperty("useServerPrepStmts", "true");
        props.setProperty("rewriteBatchedStatements", "true");
        props.setProperty("allowPublicKeyRetrieval", "true");
        props.setProperty("useSSL", "false");
        return props;
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
                "SET NAMES utf8mb4",
                "SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        };
    }

    @Override
    public String generateCreateSchema(String schemaName) {
        return "CREATE DATABASE IF NOT EXISTS " + quoteIdentifier(schemaName) +
                " CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci";
    }

    @Override
    public String generateCreateTable(DtoMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");

        if (metadata.getSchema() != null) {
            sql.append(quoteIdentifier(metadata.getSchema())).append(".");
        }

        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");

        var columnDefinitions = metadata.getFields().stream()
                .map(this::generateColumnDefinition)
                .collect(Collectors.toList());

        sql.append("  ").append(String.join(",\n  ", columnDefinitions));

        sql.append(",\n  PRIMARY KEY (")
                .append(quoteIdentifier(metadata.getIdField().getColumnName()))
                .append(")");

        var uniqueFields = metadata.getFields().stream()
                .filter(f -> f.isUnique() && !f.isId())
                .toList();

        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE KEY ")
                    .append(quoteIdentifier("uk_" + field.getColumnName()))
                    .append(" (")
                    .append(quoteIdentifier(field.getColumnName()))
                    .append(")");
        }

        sql.append("\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");

        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType(), field));
        }

        if (field.isId() && field.isAutoGenerated()) {
            def.append(" AUTO_INCREMENT");
        }

        if (!field.isNullable() && !field.isId()) {
            def.append(" NOT NULL");
        }

        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(escapeString(field.getDefaultValue())).append("'");
            } else {
                def.append(field.getDefaultValue());
            }
        }

        return def.toString();
    }

    private String escapeString(String value) {
        return value.replace("'", "''").replace("\\", "\\\\");
    }

    @Override
    public String generateUpsert(DtoMetadata metadata) {
        var allFields = metadata.getFields();
        var nonIdFields = metadata.getNonIdFields();

        String insertColumns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String insertPlaceholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        String updateSetClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = VALUES(" + quoteIdentifier(f.getColumnName()) + ")")
                .collect(Collectors.joining(", "));

        return String.format(
                "INSERT INTO %s (%s) VALUES (%s) ON DUPLICATE KEY UPDATE %s",
                getFullTableName(metadata),
                insertColumns,
                insertPlaceholders,
                updateSetClause
        );
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class) {
            int length = fieldMetadata != null ? fieldMetadata.getLength() : 255;
            if (length <= 255) {
                return "VARCHAR(" + length + ")";
            } else if (length <= 65535) {
                return "TEXT";
            } else {
                return "LONGTEXT";
            }
        } else if (javaType == Long.class || javaType == long.class) {
            return "BIGINT";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INT";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "TINYINT(1)";
        } else if (javaType == Double.class || javaType == double.class) {
            return "DOUBLE";
        } else if (javaType == Float.class || javaType == float.class) {
            return "FLOAT";
        } else if (javaType == BigDecimal.class) {
            return "DECIMAL(19, 2)";
        } else if (javaType == LocalDateTime.class) {
            return "DATETIME";
        } else if (javaType == LocalDate.class) {
            return "DATE";
        } else if (javaType == LocalTime.class) {
            return "TIME";
        } else if (javaType == Timestamp.class) {
            return "TIMESTAMP";
        } else if (javaType == byte[].class) {
            return "BLOB";
        } else if (javaType == UUID.class) {
            return "VARCHAR(36)";
        } else {
            return "TEXT";
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "`" + identifier + "`";
    }

    @Override
    public boolean supportsSchemas() {
        return true;
    }

    @Override
    public boolean supportsSequences() {
        return false;
    }

    @Override
    public boolean supportsJsonType() {
        return true;
    }

    @Override
    public boolean isEmbedded() {
        return false;
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        return "AUTO_INCREMENT";
    }

    @Override
    public String generateListTablesSQL(String schemaName) {
        if (schemaName != null) {
            return String.format(
                    "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '%s' AND TABLE_TYPE = 'BASE TABLE'",
                    schemaName
            );
        } else {
            return "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE'";
        }
    }

    @Override
    public String generateListColumnsSQL(String tableName, String schemaName) {
        if (schemaName != null) {
            return String.format(
                    "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT " +
                    "FROM INFORMATION_SCHEMA.COLUMNS " +
                    "WHERE TABLE_NAME = '%s' AND TABLE_SCHEMA = '%s'",
                    tableName, schemaName
            );
        }
        return String.format(
                "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT " +
                "FROM INFORMATION_SCHEMA.COLUMNS " +
                "WHERE TABLE_NAME = '%s' AND TABLE_SCHEMA = DATABASE()",
                tableName
        );
    }

    @Override
    public String generateAddColumn(DtoMetadata metadata, FieldMetadata field) {
        StringBuilder sql = new StringBuilder();
        sql.append("ALTER TABLE ").append(getFullTableName(metadata));
        sql.append(" ADD COLUMN ");
        sql.append(quoteIdentifier(field.getColumnName())).append(" ");
        if (field.hasCustomSqlType()) {
            sql.append(field.getSqlType());
        } else {
            sql.append(mapJavaTypeToSql(field.getJavaType(), field));
        }
        if (!field.isNullable()) {
            sql.append(" NOT NULL");
        }
        if (field.hasDefaultValue()) {
            sql.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                sql.append("'").append(escapeString(field.getDefaultValue())).append("'");
            } else {
                sql.append(field.getDefaultValue());
            }
        }
        return sql.toString();
    }

    @Override
    public String generateCreateIndex(DtoMetadata metadata, IndexDefinition index) {
        // MySQL does not support IF NOT EXISTS on CREATE INDEX
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE ");
        if (index.unique()) {
            sql.append("UNIQUE ");
        }
        sql.append("INDEX ");
        sql.append(quoteIdentifier(index.name()));
        sql.append(" ON ");
        sql.append(getFullTableName(metadata));
        sql.append(" (");
        for (int i = 0; i < index.columns().length; i++) {
            if (i > 0) sql.append(", ");
            sql.append(quoteIdentifier(index.columns()[i]));
        }
        sql.append(")");
        // MySQL does not support partial indexes
        return sql.toString();
    }

    @Override
    public String generateCreateJoinTable(String joinTable, String leftColumn, Class<?> leftIdType,
                                          String rightColumn, Class<?> rightIdType) {
        return String.format(
            "CREATE TABLE IF NOT EXISTS %s (%s %s NOT NULL, %s %s NOT NULL, PRIMARY KEY (%s, %s)) ENGINE=InnoDB",
            quoteIdentifier(joinTable),
            quoteIdentifier(leftColumn), mapJavaTypeToSql(leftIdType, null),
            quoteIdentifier(rightColumn), mapJavaTypeToSql(rightIdType, null),
            quoteIdentifier(leftColumn), quoteIdentifier(rightColumn)
        );
    }
}