package fr.traqueur.victor.registries;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.entities.Dto;
import fr.traqueur.victor.entities.Entity;
import fr.traqueur.victor.entities.metadata.DtoMetadata;
import fr.traqueur.victor.exceptions.VictorConfigurationException;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DtoMetadataTest {

    static class TestUserModel implements Entity<Long> {
        private Long id;
        private String username;
        @Override public Long getId() { return id; }
        @Override public void setId(Long id) { this.id = id; }
    }

    @Table(table = "test_users", schema = "test_schema")
    record TestUserDto(
        @Id(autoGenerated = true) Long id,
        @Column(nullable = false, unique = true, length = 50) String username,
        @Column(nullable = false, defaultValue = "user@example.com") String email,
        @Column(sqlType = "TEXT") String description
    ) implements Dto<TestUserModel> {
        @Override public TestUserModel toModel() { return new TestUserModel(); }
    }

    static class InvalidClass {}

    static class InvalidUserModel implements Entity<Long> {
        private Long id;
        @Override public Long getId() { return id; }
        @Override public void setId(Long id) { this.id = id; }
    }

    // No @Table annotation — should throw
    record InvalidUserDto(Long id, String name) implements Dto<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    @Table(table = "multi_id_users")
    record MultipleIdDto(
        @Id Long id1,
        @Id Long id2
    ) implements Dto<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    @Test
    void testDtoMetadataCreation() {
        var metadata = DtoMetadata.of(TestUserDto.class);

        assertEquals("test_users", metadata.getTableName());
        assertEquals("test_schema", metadata.getSchema());
        assertEquals("test_schema.test_users", metadata.getFullTableName());
    }

    @Test
    void testIdFieldDetection() {
        var metadata = DtoMetadata.of(TestUserDto.class);
        var idField = metadata.getIdField();

        assertNotNull(idField);
        assertTrue(idField.isId());
        assertTrue(idField.isAutoGenerated());
        assertEquals("id", idField.getColumnName());
        assertEquals(Long.class, idField.getJavaType());
    }

    @Test
    void testFieldsAnalysis() {
        var metadata = DtoMetadata.of(TestUserDto.class);
        var fields = metadata.getScalarFields();

        assertEquals(4, fields.size()); // id, username, email, description

        var usernameField = metadata.getFieldByColumn("username");
        assertNotNull(usernameField);
        assertFalse(usernameField.isNullable());
        assertTrue(usernameField.isUnique());
        assertEquals(50, usernameField.getLength());

        var emailField = metadata.getFieldByColumn("email");
        assertNotNull(emailField);
        assertEquals("user@example.com", emailField.getDefaultValue());

        var descField = metadata.getFieldByColumn("description");
        assertNotNull(descField);
        assertEquals("TEXT", descField.getSqlType());
        assertTrue(descField.hasCustomSqlType());
    }

    @Test
    void testFieldMetadataGetValue() {
        var dto = new TestUserDto(1L, "testuser", "test@test.com", "desc");
        var metadata = DtoMetadata.of(TestUserDto.class);
        var usernameField = metadata.getFieldByColumn("username");

        assertNotNull(usernameField);
        assertEquals("testuser", usernameField.getValue(dto));
    }

    @Test
    void testMissingTableAnnotation() {
        assertThrows(VictorConfigurationException.class, () ->
            DtoMetadata.of(InvalidUserDto.class)
        );
    }

    @Test
    void testMultipleIdFields() {
        assertThrows(VictorConfigurationException.class, () ->
            DtoMetadata.of(MultipleIdDto.class)
        );
    }

    @Test
    void testDtoMetadataRegistry() {
        var registry = DtoMetadataRegistry.getInstance();

        var metadata1 = registry.getMetadata(TestUserDto.class);
        var metadata2 = registry.getMetadata(TestUserDto.class);

        assertSame(metadata1, metadata2); // Should be cached
    }
}