package fr.traqueur.victor.registries;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.entity.Entity;
import fr.traqueur.victor.entity.Model;
import fr.traqueur.victor.entity.metadata.EntityMetadata;
import fr.traqueur.victor.exceptions.VictorConfigurationException;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class EntityMetadataTest {

    static class TestUserModel implements Model<Long> {
        private Long id;
        private String username;
        @Override public Long getId() { return id; }
        @Override public void setId(Long id) { this.id = id; }
    }

    @Table(table = "test_users", schema = "test_schema")
    record TestUserEntity(
        @Id(autoGenerated = true) Long id,
        @Column(nullable = false, unique = true, length = 50) String username,
        @Column(nullable = false, defaultValue = "user@example.com") String email,
        @Column(sqlType = "TEXT") String description
    ) implements Entity<TestUserModel> {
        @Override public TestUserModel toModel() { return new TestUserModel(); }
    }

    static class InvalidClass {}

    static class InvalidUserModel implements Model<Long> {
        private Long id;
        @Override public Long getId() { return id; }
        @Override public void setId(Long id) { this.id = id; }
    }

    // No @Table annotation — should throw
    record InvalidUserEntity(Long id, String name) implements Entity<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    @Table(table = "multi_id_users")
    record MultipleIdEntity(
        @Id Long id1,
        @Id Long id2
    ) implements Entity<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    // Class-based entity (not a record) — must be rejected: entities are record-only.
    @Table(table = "class_users")
    static class ClassBasedEntity implements Entity<InvalidUserModel> {
        @Id Long id;
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    // --- @Embedded fixtures ---

    record EmbAudit(java.time.LocalDateTime createdAt, @Column(length = 80) String createdBy) {}

    @Table(table = "emb_invoices")
    record EmbeddedEntity(
        @Id Long id,
        @Column String number,
        @Embedded EmbAudit audit
    ) implements Entity<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    static class NotARecord { }

    @Table(table = "bad_emb")
    record NonRecordEmbedded(@Id Long id, @Embedded NotARecord bad) implements Entity<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    record EmbWithId(@Id Long innerId, String label) {}

    @Table(table = "bad_emb_id")
    record EmbeddedWithIdEntity(@Id Long id, @Embedded EmbWithId e) implements Entity<InvalidUserModel> {
        @Override public InvalidUserModel toModel() { return new InvalidUserModel(); }
    }

    @Test
    void testEntityMetadataCreation() {
        var metadata = EntityMetadata.of(TestUserEntity.class);

        assertEquals("test_users", metadata.getTableName());
        assertEquals("test_schema", metadata.getSchema());
        assertEquals("test_schema.test_users", metadata.getFullTableName());
    }

    @Test
    void testIdFieldDetection() {
        var metadata = EntityMetadata.of(TestUserEntity.class);
        var idField = metadata.getIdField();

        assertNotNull(idField);
        assertTrue(idField.isId());
        assertTrue(idField.isAutoGenerated());
        assertEquals("id", idField.getColumnName());
        assertEquals(Long.class, idField.getJavaType());
    }

    @Test
    void testFieldsAnalysis() {
        var metadata = EntityMetadata.of(TestUserEntity.class);
        var fields = metadata.getScalarFields();

        assertEquals(4, fields.size()); // id, username, email, description

        var usernameField = metadata.getFieldByColumn("username");
        assertNotNull(usernameField);
        assertFalse(usernameField.isNullable());
        assertTrue(usernameField.isUnique());
        assertEquals(50, usernameField.getLength());

        var emailField = metadata.getFieldByColumn("email");
        assertNotNull(emailField);
        assertEquals("user@example.com", emailField.getDefaultValue());

        var descField = metadata.getFieldByColumn("description");
        assertNotNull(descField);
        assertEquals("TEXT", descField.getSqlType());
        assertTrue(descField.hasCustomSqlType());
    }

    @Test
    void testFieldMetadataGetValue() {
        var entity = new TestUserEntity(1L, "testuser", "test@test.com", "desc");
        var metadata = EntityMetadata.of(TestUserEntity.class);
        var usernameField = metadata.getFieldByColumn("username");

        assertNotNull(usernameField);
        assertEquals("testuser", usernameField.getValue(entity));
    }

    @Test
    void testMissingTableAnnotation() {
        assertThrows(VictorConfigurationException.class, () ->
            EntityMetadata.of(InvalidUserEntity.class)
        );
    }

    @Test
    void testMultipleIdFields() {
        assertThrows(VictorConfigurationException.class, () ->
            EntityMetadata.of(MultipleIdEntity.class)
        );
    }

    @Test
    void testClassBasedEntityIsRejected() {
        // Entities must be Java records; a class-based entity must be rejected.
        assertThrows(VictorConfigurationException.class, () ->
            EntityMetadata.of(ClassBasedEntity.class)
        );
    }

    @Test
    void testEmbeddedFlattensColumns() {
        var metadata = EntityMetadata.of(EmbeddedEntity.class);

        var columns = metadata.getFields().stream()
                .map(f -> f.getColumnName())
                .toList();
        assertTrue(columns.contains("created_at"));
        assertTrue(columns.contains("created_by"));
        assertTrue(columns.contains("number"));

        assertEquals(1, metadata.getEmbeddeds().size());
        assertNotNull(metadata.findEmbeddedByFieldName("audit"));
        assertEquals(2, metadata.findEmbeddedByFieldName("audit").getSubFields().size());
    }

    @Test
    void testEmbeddedNonRecordTypeIsRejected() {
        assertThrows(VictorConfigurationException.class, () ->
            EntityMetadata.of(NonRecordEmbedded.class)
        );
    }

    @Test
    void testEmbeddedWithIdIsRejected() {
        assertThrows(VictorConfigurationException.class, () ->
            EntityMetadata.of(EmbeddedWithIdEntity.class)
        );
    }

    @Test
    void testEntityMetadataRegistry() {
        var registry = EntityMetadataRegistry.getInstance();

        var metadata1 = registry.getMetadata(TestUserEntity.class);
        var metadata2 = registry.getMetadata(TestUserEntity.class);

        assertSame(metadata1, metadata2); // Should be cached
    }
}