package fr.traqueur.victor.registries;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.entities.Entity;
import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.exceptions.VictorConfigurationException;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class EntityMetadataTest {
    
    @Table(table = "test_users", schema = "test_schema")
    static class TestUser implements Entity<Long> {
        @Id(autoGenerated = true)
        private Long id;
        
        @Column(nullable = false, unique = true, length = 50)
        private String username;
        
        @Column(nullable = false, defaultValue = "user@example.com")
        private String email;
        
        @Column(sqlType = "TEXT")
        private String description;
        
        @Ignore
        private String ignoredField;
        
        @Override
        public Long getId() { return id; }
        @Override
        public void setId(Long id) { this.id = id; }
    }
    
    static class InvalidUser {
        private Long id;
    }
    
    @Table(table = "multi_id_users")
    static class MultipleIdUser implements Entity<Long> {
        @Id
        private Long id1;
        
        @Id
        private Long id2;
        
        @Override
        public Long getId() { return id1; }
        @Override
        public void setId(Long id) { this.id1 = id; }
    }
    
    @Test
    void testEntityMetadataCreation() {
        var metadata = EntityMetadata.of(TestUser.class);
        
        assertEquals(TestUser.class, metadata.getEntityClass());
        assertEquals("test_users", metadata.getTableName());
        assertEquals("test_schema", metadata.getSchema());
        assertEquals("test_schema.test_users", metadata.getFullTableName());
    }
    
    @Test
    void testIdFieldDetection() {
        var metadata = EntityMetadata.of(TestUser.class);
        var idField = metadata.getIdField();
        
        assertNotNull(idField);
        assertTrue(idField.isId());
        assertTrue(idField.isAutoGenerated());
        assertEquals("id", idField.getColumnName());
        assertEquals(Long.class, idField.getJavaType());
    }
    
    @Test
    void testFieldsAnalysis() {
        var metadata = EntityMetadata.of(TestUser.class);
        var fields = metadata.getFields();
        
        assertEquals(4, fields.size()); // id, username, email, description (ignoredField excluded)
        
        var usernameField = metadata.getField("username");
        assertNotNull(usernameField);
        assertFalse(usernameField.isNullable());
        assertTrue(usernameField.isUnique());
        assertEquals(50, usernameField.getLength());
        
        var emailField = metadata.getField("email");
        assertNotNull(emailField);
        assertEquals("user@example.com", emailField.getDefaultValue());
        
        var descField = metadata.getField("description");
        assertNotNull(descField);
        assertEquals("TEXT", descField.getSqlType());
        assertTrue(descField.hasCustomSqlType());
    }
    
    @Test
    void testFieldMetadataGetSet() throws Exception {
        var user = new TestUser();
        var metadata = EntityMetadata.of(TestUser.class);
        var usernameField = metadata.getField("username");
        
        usernameField.setValue(user, "testuser");
        assertEquals("testuser", usernameField.getValue(user));
    }
    
    @Test
    void testInvalidEntityClass() {
        assertThrows(VictorConfigurationException.class, () -> {
            EntityMetadata.of(InvalidUser.class);
        });
    }
    
    @Test
    void testMultipleIdFields() {
        assertThrows(VictorConfigurationException.class, () -> {
            EntityMetadata.of(MultipleIdUser.class);
        });
    }
    
    @Test
    void testMetadataRegistry() {
        var registry = EntityMetadataRegistry.getInstance();
        
        var metadata1 = registry.getMetadata(TestUser.class);
        var metadata2 = registry.getMetadata(TestUser.class);
        
        assertSame(metadata1, metadata2); // Should be cached
        assertTrue(registry.isRegistered(TestUser.class));
    }
}