package fr.traqueur.victor.entity.metadata;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.exceptions.VictorException;
import fr.traqueur.victor.utils.StringUtils;

import java.lang.reflect.Method;
import java.lang.reflect.RecordComponent;

public final class FieldMetadata {

    private final RecordComponent recordComponent; // null for synthetic FK fields
    private final Method recordAccessor;           // null for synthetic FK fields
    private final Method embeddedAccessor;         // non-null only for embedded sub-fields (parent -> embedded)
    private final String columnName;
    private final Class<?> javaType;
    private final boolean nullable;
    private final int length;
    private final boolean unique;
    private final String defaultValue;
    private final String sqlType;
    private final boolean isId;
    private final boolean autoGenerated;
    private final String sequence;

    // Constructor for record components (record-based E)
    private FieldMetadata(RecordComponent component) {
        this(component, null, "");
    }

    // Constructor for record components, optionally as an embedded sub-field
    // (embeddedAccessor = parent accessor, columnPrefix = optional column prefix).
    private FieldMetadata(RecordComponent component, Method embeddedAccessor, String columnPrefix) {
        this.recordComponent = component;
        this.recordAccessor = component.getAccessor();
        this.recordAccessor.setAccessible(true);
        this.embeddedAccessor = embeddedAccessor;
        this.javaType = component.getType();

        var column = component.getAnnotation(Column.class);
        String baseColumn = (column != null && !column.name().isEmpty()) ?
            column.name() : StringUtils.camelToSnakeCase(component.getName());
        this.columnName = (columnPrefix == null || columnPrefix.isEmpty())
            ? baseColumn : columnPrefix + baseColumn;

        this.nullable = column == null || column.nullable();
        this.length = column != null ? column.length() : 255;
        this.unique = column != null && column.unique();
        this.defaultValue = column != null ? column.defaultValue() : "";
        this.sqlType = column != null ? column.sqlType() : "";

        this.isId = component.getAnnotation(Id.class) != null;

        if (isId) {
            var id = component.getAnnotation(Id.class);
            this.autoGenerated = id.autoGenerated();
            this.sequence = id.sequence().isEmpty() ? null : id.sequence();
        } else {
            this.autoGenerated = false;
            this.sequence = null;
        }
    }

    // Constructor for synthetic FK fields (no backing Java field — created by relationship metadata)
    private FieldMetadata(String columnName, Class<?> javaType, boolean nullable) {
        this.recordComponent = null;
        this.recordAccessor = null;
        this.embeddedAccessor = null;
        this.columnName = columnName;
        this.javaType = javaType;
        this.nullable = nullable;
        this.length = 255;
        this.unique = false;
        this.defaultValue = "";
        this.sqlType = "";
        this.isId = false;
        this.autoGenerated = false;
        this.sequence = null;
    }

    public static FieldMetadata ofRecordComponent(RecordComponent component) {
        return new FieldMetadata(component);
    }

    /**
     * Creates a flattened column descriptor for a sub-component of an {@code @Embedded}
     * record. {@code parentAccessor} is the owning entity accessor returning the
     * embedded instance; {@code columnPrefix} is prepended to the column name.
     */
    public static FieldMetadata forEmbedded(RecordComponent subComponent, Method parentAccessor, String columnPrefix) {
        return new FieldMetadata(subComponent, parentAccessor, columnPrefix);
    }

    /**
     * Creates a synthetic FK column descriptor used by AutoMigration and SQL generators.
     * This field has no backing Java field — it represents a FK column whose value
     * is extracted from the related E's ID at save time.
     */
    public static FieldMetadata forForeignKey(String columnName, Class<?> idJavaType, boolean nullable) {
        return new FieldMetadata(columnName, idJavaType, nullable);
    }

    public Object getValue(Object obj) {
        try {
            if (recordAccessor == null) {
                return null; // synthetic FK — no backing accessor
            }
            if (embeddedAccessor != null) {
                Object embedded = embeddedAccessor.invoke(obj);
                return embedded == null ? null : recordAccessor.invoke(embedded);
            if (recordAccessor != null) {
                return recordAccessor.invoke(obj);
            }
            return recordAccessor.invoke(obj);
        } catch (Exception e) {
            throw new VictorException("Failed to get value from field: " + columnName, e);
        }
    }

    /** Returns the field name in the record (used to match E fields by name). */
    public String getFieldName() {
        if (recordComponent != null) return recordComponent.getName();
        return columnName; // synthetic FK — use column name as fallback
    }

    public RecordComponent getRecordComponent() { return recordComponent; }
    public String getColumnName() { return columnName; }
    public Class<?> getJavaType() { return javaType; }
    public boolean isNullable() { return nullable; }
    public int getLength() { return length; }
    public boolean isUnique() { return unique; }
    public String getDefaultValue() { return defaultValue; }
    public String getSqlType() { return sqlType; }
    public boolean isId() { return isId; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public String getSequence() { return sequence; }

    public boolean hasCustomSqlType() {
        return !sqlType.isEmpty();
    }

    public boolean hasDefaultValue() {
        return !defaultValue.isEmpty();
    }

    public boolean isSyntheticFk() {
        return recordComponent == null;
    }

    /** True when this column is a flattened sub-field of an {@code @Embedded} component. */
    public boolean isEmbeddedSubField() {
        return embeddedAccessor != null;
    }
}