package fr.traqueur.victor.entity.metadata;

import fr.traqueur.victor.annotations.*;
import fr.traqueur.victor.exceptions.VictorException;
import fr.traqueur.victor.utils.StringUtils;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.RecordComponent;

public final class FieldMetadata {

    private final Field field;                    // null for record-component or synthetic FK fields
    private final RecordComponent recordComponent; // null for class fields and synthetic FK fields
    private final Method recordAccessor;           // null for class fields and synthetic FK fields
    private final String columnName;
    private final Class<?> javaType;
    private final boolean nullable;
    private final int length;
    private final boolean unique;
    private final String defaultValue;
    private final String sqlType;
    private final boolean isId;
    private final boolean autoGenerated;
    private final String sequence;

    // Constructor for class fields (Model or class-based E)
    private FieldMetadata(Field field) {
        this.field = field;
        this.field.setAccessible(true);
        this.recordComponent = null;
        this.recordAccessor = null;
        this.javaType = field.getType();

        var column = field.getAnnotation(Column.class);
        this.columnName = (column != null && !column.name().isEmpty()) ?
            column.name() : StringUtils.camelToSnakeCase(field.getName());

        this.nullable = column == null || column.nullable();
        this.length = column != null ? column.length() : 255;
        this.unique = column != null && column.unique();
        this.defaultValue = column != null ? column.defaultValue() : "";
        this.sqlType = column != null ? column.sqlType() : "";

        this.isId = field.isAnnotationPresent(Id.class);

        if (isId) {
            var id = field.getAnnotation(Id.class);
            this.autoGenerated = id.autoGenerated();
            this.sequence = id.sequence().isEmpty() ? null : id.sequence();
        } else {
            this.autoGenerated = false;
            this.sequence = null;
        }
    }

    // Constructor for record components (record-based E)
    private FieldMetadata(RecordComponent component) {
        this.field = null;
        this.recordComponent = component;
        this.recordAccessor = component.getAccessor();
        this.recordAccessor.setAccessible(true);
        this.javaType = component.getType();

        var column = component.getAnnotation(Column.class);
        this.columnName = (column != null && !column.name().isEmpty()) ?
            column.name() : StringUtils.camelToSnakeCase(component.getName());

        this.nullable = column == null || column.nullable();
        this.length = column != null ? column.length() : 255;
        this.unique = column != null && column.unique();
        this.defaultValue = column != null ? column.defaultValue() : "";
        this.sqlType = column != null ? column.sqlType() : "";

        this.isId = component.getAnnotation(Id.class) != null;

        if (isId) {
            var id = component.getAnnotation(Id.class);
            this.autoGenerated = id.autoGenerated();
            this.sequence = id.sequence().isEmpty() ? null : id.sequence();
        } else {
            this.autoGenerated = false;
            this.sequence = null;
        }
    }

    // Constructor for synthetic FK fields (no backing Java field — created by relationship metadata)
    private FieldMetadata(String columnName, Class<?> javaType, boolean nullable) {
        this.field = null;
        this.recordComponent = null;
        this.recordAccessor = null;
        this.columnName = columnName;
        this.javaType = javaType;
        this.nullable = nullable;
        this.length = 255;
        this.unique = false;
        this.defaultValue = "";
        this.sqlType = "";
        this.isId = false;
        this.autoGenerated = false;
        this.sequence = null;
    }

    public static FieldMetadata of(Field field) {
        return new FieldMetadata(field);
    }

    public static FieldMetadata ofRecordComponent(RecordComponent component) {
        return new FieldMetadata(component);
    }

    /**
     * Creates a synthetic FK column descriptor used by AutoMigration and SQL generators.
     * This field has no backing Java field — it represents a FK column whose value
     * is extracted from the related E's ID at save time.
     */
    public static FieldMetadata forForeignKey(String columnName, Class<?> idJavaType, boolean nullable) {
        return new FieldMetadata(columnName, idJavaType, nullable);
    }

    public Object getValue(Object obj) {
        try {
            if (recordAccessor != null) {
                return recordAccessor.invoke(obj);
            } else if (field != null) {
                return field.get(obj);
            }
            return null;
        } catch (Exception e) {
            throw new VictorException("Failed to get value from field: " + columnName, e);
        }
    }

    public void setValue(Object obj, Object value) {
        if (field == null) {
            // Records are immutable and synthetic fields have no backing field — no-op.
            return;
        }
        try {
            field.set(obj, value);
        } catch (IllegalAccessException e) {
            throw new VictorException("Failed to set value to field: " + field, e);
        }
    }

    /** Returns the field name in the Java class/record (used to match E fields by name). */
    public String getFieldName() {
        if (recordComponent != null) return recordComponent.getName();
        if (field != null) return field.getName();
        return columnName; // synthetic FK — use column name as fallback
    }

    public Field getField() { return field; }
    public RecordComponent getRecordComponent() { return recordComponent; }
    public String getColumnName() { return columnName; }
    public Class<?> getJavaType() { return javaType; }
    public boolean isNullable() { return nullable; }
    public int getLength() { return length; }
    public boolean isUnique() { return unique; }
    public String getDefaultValue() { return defaultValue; }
    public String getSqlType() { return sqlType; }
    public boolean isId() { return isId; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public String getSequence() { return sequence; }

    public boolean hasCustomSqlType() {
        return !sqlType.isEmpty();
    }

    public boolean hasDefaultValue() {
        return !defaultValue.isEmpty();
    }

    public boolean isSyntheticFk() {
        return field == null && recordComponent == null;
    }
}