package fr.traqueur.victor.entities.dialect.h2;

import fr.traqueur.victor.entities.dialect.Dialect;
import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;

import java.util.Properties;
import java.util.stream.Collectors;

public class H2Dialect implements Dialect {

    @Override
    public String getName() {
        return "h2";
    }

    @Override
    public String getDriverClassName() {
        return "org.h2.Driver";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:h2:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        if (host != null && port > 0) {
            // TCP mode: jdbc:h2:tcp://localhost:9092/~/test
            return String.format("jdbc:h2:tcp://%s:%d/%s", host, port, database);
        } else {
            // Embedded mode: jdbc:h2:mem:test or jdbc:h2:file:test
            if (database.startsWith("mem:") || database.startsWith("file:")) {
                return "jdbc:h2:" + database;
            } else {
                return "jdbc:h2:mem:" + database;
            }
        }
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        Properties props = new Properties();
        props.setProperty("DB_CLOSE_ON_EXIT", "FALSE");
        props.setProperty("DB_CLOSE_DELAY", "-1");
        props.setProperty("MODE", "MySQL"); // MySQL compatibility mode
        return props;
    }

    @Override
    public String generateCreateTable(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");
        
        if (metadata.getSchema() != null) {
            sql.append(quoteIdentifier(metadata.getSchema())).append(".");
        }
        
        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");
        
        // Add columns
        var columnDefinitions = metadata.getFields().stream()
            .map(this::generateColumnDefinition)
            .collect(Collectors.toList());
        
        sql.append("  ").append(String.join(",\n  ", columnDefinitions));
        
        // Add primary key
        sql.append(",\n  PRIMARY KEY (").append(quoteIdentifier(metadata.getIdField().getColumnName())).append(")");
        
        // Add unique constraints
        var uniqueFields = metadata.getFields().stream()
            .filter(f -> f.isUnique() && !f.isId())
            .toList();
        
        for (FieldMetadata field : uniqueFields) {
            sql.append(",\n  UNIQUE (").append(quoteIdentifier(field.getColumnName())).append(")");
        }
        
        sql.append("\n)");
        
        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");
        
        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            def.append(mapJavaTypeToSql(field.getJavaType(), field));
        }
        
        // Auto increment for ID
        if (field.isId() && field.isAutoGenerated()) {
            def.append(" AUTO_INCREMENT");
        }
        
        // NOT NULL
        if (!field.isNullable()) {
            def.append(" NOT NULL");
        }
        
        // Default value
        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(field.getDefaultValue()).append("'");
            } else {
                def.append(field.getDefaultValue());
            }
        }
        
        return def.toString();
    }

    @Override
    public String generateUpsert(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("MERGE INTO ").append(getFullTableName(metadata));

        var allFields = metadata.getFields();
        String columns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String placeholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        sql.append(" (").append(columns).append(")")
                .append(" KEY(").append(quoteIdentifier(metadata.getIdField().getColumnName())).append(")")
                .append(" VALUES (").append(placeholders).append(")");

        return sql.toString();
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class) {
            return "VARCHAR(" + fieldMetadata.getLength() + ")";
        } else if (javaType == Long.class || javaType == long.class) {
            return "BIGINT";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INTEGER";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "BOOLEAN";
        } else if (javaType == Double.class || javaType == double.class) {
            return "DOUBLE";
        } else if (javaType == Float.class || javaType == float.class) {
            return "REAL";
        } else if (javaType == java.time.LocalDateTime.class) {
            return "TIMESTAMP";
        } else if (javaType == java.util.UUID.class) {
            return "UUID";
        } else {
            return "CLOB"; // Default for unknown types
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier + "\"";
    }

    @Override
    public boolean supportsSchemas() {
        return true;
    }

    @Override
    public boolean supportsSequences() {
        return true;
    }

    @Override
    public boolean supportsJsonType() {
        return false; // H2 doesn't have native JSON support
    }

    @Override
    public boolean isEmbedded() {
        return true;
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        return "AUTO_INCREMENT";
    }

    @Override
    public String generateListTablesSQL(String schemaName) {
        if (schemaName != null) {
            return String.format(
                    "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '%s' AND TABLE_TYPE = 'TABLE'",
                    schemaName.toUpperCase()
            );
        } else {
            return "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'TABLE'";
        }
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
            "SET MODE MySQL", // MySQL compatibility
            "SET DB_CLOSE_DELAY -1" // Keep database open
        };
    }
}