package fr.traqueur.victor.entities.dialect.postregresql;

import fr.traqueur.victor.entities.dialect.Dialect;
import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Properties;
import java.util.stream.Collectors;

public class PostegreSQLDialect implements Dialect {
    @Override
    public String getName() {
        return "postgresql";
    }

    @Override
    public String getDriverClassName() {
        return "org.postgresql.Driver";
    }

    @Override
    public boolean supportsUrl(String jdbcUrl) {
        return jdbcUrl.startsWith("jdbc:postgresql:");
    }

    @Override
    public String buildConnectionUrl(String host, int port, String database, Properties properties) {
        if (port == 0) {
            port = 5432;
        }

        StringBuilder url = new StringBuilder();
        url.append("jdbc:postgresql://")
                .append(host)
                .append(":")
                .append(port)
                .append("/")
                .append(database);

        if (!properties.isEmpty()) {
            url.append("?");
            properties.forEach((key, value) -> {
                url.append(key).append("=").append(value).append("&");
            });
            url.setLength(url.length() - 1);
        }

        return url.toString();
    }

    @Override
    public String[] getConnectionSetupSql() {
        return new String[]{
                "SET search_path TO public",
                "SET CLIENT_ENCODING TO 'UTF8'"
        };
    }

    @Override
    public Properties getDefaultConnectionProperties() {
        Properties props = new Properties();

        props.setProperty("charSet", "UTF8");

        props.setProperty("prepareThreshold", "5");
        props.setProperty("preparedStatementCacheQueries", "256");
        props.setProperty("preparedStatementCacheSizeMiB", "5");

        props.setProperty("connectTimeout", "10");
        props.setProperty("socketTimeout", "30");

        props.setProperty("ApplicationName", "Victor-ORM");

        props.setProperty("ssl", "false");
        props.setProperty("sslmode", "prefer");

        return props;
    }

    @Override
    public String generateCreateSchema(String schemaName) {
        return "CREATE SCHEMA IF NOT EXISTS " + quoteIdentifier(schemaName);
    }

    @Override
    public String generateCreateTable(EntityMetadata metadata) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");

        if (metadata.getSchema() != null) {
            sql.append(quoteIdentifier(metadata.getSchema())).append(".");
        }

        sql.append(quoteIdentifier(metadata.getTableName())).append(" (\n");

        // Colonnes
        var columnDefinitions = metadata.getFields().stream()
                .map(this::generateColumnDefinition)
                .collect(Collectors.toList());

        sql.append("  ").append(String.join(",\n  ", columnDefinitions));

        String pkName = "pk_" + metadata.getTableName();
        sql.append(",\n  CONSTRAINT ")
                .append(quoteIdentifier(pkName))
                .append(" PRIMARY KEY (")
                .append(quoteIdentifier(metadata.getIdField().getColumnName()))
                .append(")");

        var uniqueFields = metadata.getFields().stream()
                .filter(f -> f.isUnique() && !f.isId())
                .toList();

        for (FieldMetadata field : uniqueFields) {
            String ukName = "uk_" + metadata.getTableName() + "_" + field.getColumnName();
            sql.append(",\n  CONSTRAINT ")
                    .append(quoteIdentifier(ukName))
                    .append(" UNIQUE (")
                    .append(quoteIdentifier(field.getColumnName()))
                    .append(")");
        }

        sql.append("\n)");

        return sql.toString();
    }

    private String generateColumnDefinition(FieldMetadata field) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(field.getColumnName())).append(" ");

        if (field.hasCustomSqlType()) {
            def.append(field.getSqlType());
        } else {
            if (field.isId() && field.isAutoGenerated()) {
                def.append(getAutoIncrementSyntax(field.getJavaType()));
            } else {
                def.append(mapJavaTypeToSql(field.getJavaType(), field));
            }
        }

        if (!field.isNullable() && !(field.isId() && field.isAutoGenerated())) {
            def.append(" NOT NULL");
        }

        // Default value
        if (field.hasDefaultValue()) {
            def.append(" DEFAULT ");
            if (field.getJavaType() == String.class) {
                def.append("'").append(escapeString(field.getDefaultValue())).append("'");
            } else if (field.getJavaType() == Boolean.class || field.getJavaType() == boolean.class) {
                def.append(field.getDefaultValue());
            } else {
                def.append(field.getDefaultValue());
            }
        }

        return def.toString();
    }

    private String escapeString(String value) {
        return value.replace("'", "''");
    }

    @Override
    public String generateInsert(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String columns = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String placeholders = nonIdFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        return String.format("INSERT INTO %s (%s) VALUES (%s)",
                getFullTableName(metadata), columns, placeholders);
    }

    @Override
    public String generateUpdate(EntityMetadata metadata) {
        var nonIdFields = metadata.getNonIdFields();
        String setClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = ?")
                .collect(Collectors.joining(", "));

        return String.format("UPDATE %s SET %s WHERE %s = ?",
                getFullTableName(metadata),
                setClause,
                quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateUpsert(EntityMetadata metadata) {

        var allFields = metadata.getFields();
        var nonIdFields = metadata.getNonIdFields();

        String insertColumns = allFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        String insertPlaceholders = allFields.stream()
                .map(f -> "?")
                .collect(Collectors.joining(", "));

        String updateSetClause = nonIdFields.stream()
                .map(f -> quoteIdentifier(f.getColumnName()) + " = EXCLUDED." + quoteIdentifier(f.getColumnName()))
                .collect(Collectors.joining(", "));

        return String.format(
                "INSERT INTO %s (%s) VALUES (%s) ON CONFLICT (%s) DO UPDATE SET %s",
                getFullTableName(metadata),
                insertColumns,
                insertPlaceholders,
                quoteIdentifier(metadata.getIdField().getColumnName()),
                updateSetClause
        );
    }

    @Override
    public String generateDelete(EntityMetadata metadata) {
        return String.format("DELETE FROM %s WHERE %s = ?",
                getFullTableName(metadata),
                quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateSelectById(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s WHERE %s = ?",
                getFullTableName(metadata),
                quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String generateSelectAll(EntityMetadata metadata) {
        return String.format("SELECT * FROM %s", getFullTableName(metadata));
    }

    @Override
    public String generateCount(EntityMetadata metadata) {
        return String.format("SELECT COUNT(*) FROM %s", getFullTableName(metadata));
    }

    @Override
    public String generateExists(EntityMetadata metadata) {
        return String.format("SELECT EXISTS(SELECT 1 FROM %s WHERE %s = ?)",
                getFullTableName(metadata),
                quoteIdentifier(metadata.getIdField().getColumnName()));
    }

    @Override
    public String mapJavaTypeToSql(Class<?> javaType, FieldMetadata fieldMetadata) {
        if (javaType == String.class) {
            int length = fieldMetadata.getLength();
            if (length <= 255) {
                return "VARCHAR(" + length + ")";
            } else {
                return "TEXT";
            }
        } else if (javaType == Long.class || javaType == long.class) {
            return "BIGINT";
        } else if (javaType == Integer.class || javaType == int.class) {
            return "INTEGER";
        } else if (javaType == Boolean.class || javaType == boolean.class) {
            return "BOOLEAN";
        } else if (javaType == Double.class || javaType == double.class) {
            return "DOUBLE PRECISION";
        } else if (javaType == Float.class || javaType == float.class) {
            return "REAL";
        } else if (javaType == BigDecimal.class) {
            return "NUMERIC(19, 2)";
        } else if (javaType == LocalDateTime.class) {
            return "TIMESTAMP";
        } else if (javaType == LocalDate.class) {
            return "DATE";
        } else if (javaType == LocalTime.class) {
            return "TIME";
        } else if (javaType == Timestamp.class) {
            return "TIMESTAMP";
        } else if (javaType == byte[].class) {
            return "BYTEA";
        } else if (javaType == java.util.UUID.class) {
            return "UUID";
        } else {
            return "TEXT";  // Fallback
        }
    }

    @Override
    public String quoteIdentifier(String identifier) {
        return "\"" + identifier.toLowerCase() + "\"";
    }

    @Override
    public String escapeLikePattern(String pattern) {
        return pattern.replace("\\", "\\\\")
                .replace("%", "\\%")
                .replace("_", "\\_");
    }

    @Override
    public boolean supportsSchemas() {
        return true;
    }

    @Override
    public boolean supportsSequences() {
        return true;
    }

    @Override
    public boolean supportsJsonType() {
        return true;
    }

    @Override
    public boolean isEmbedded() {
        return false;
    }

    private String getFullTableName(EntityMetadata metadata) {
        if (metadata.getSchema() != null) {
            return quoteIdentifier(metadata.getSchema()) + "." +
                    quoteIdentifier(metadata.getTableName());
        } else {
            return quoteIdentifier(metadata.getTableName());
        }
    }

    @Override
    public String getAutoIncrementSyntax(Class<?> idType) {
        if (idType == Long.class || idType == long.class) {
            return "BIGSERIAL";
        } else {
            return "SERIAL";
        }
    }
}
