package fr.traqueur.victor.proxy;

import fr.traqueur.victor.entities.Dto;
import fr.traqueur.victor.entities.Entity;
import fr.traqueur.victor.entities.Query;
import fr.traqueur.victor.entities.Repository;
import fr.traqueur.victor.entities.metadata.EntityMetadata;
import fr.traqueur.victor.entities.metadata.FieldMetadata;
import fr.traqueur.victor.exceptions.VictorEntityNotFoundException;
import fr.traqueur.victor.registries.EntityMetadataRegistry;
import fr.traqueur.victor.reflections.TypeResolver;
import fr.traqueur.victor.database.SqlExecutor;
import fr.traqueur.victor.entities.dialect.Dialect; // ✅ CHANGEMENT: Dialect au lieu de SqlGenerator
import fr.traqueur.victor.database.DtoMapper;
import fr.traqueur.victor.exceptions.VictorException;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.List;
import java.util.Optional;
import java.util.stream.StreamSupport;

public class RepositoryProxyHandler<DTO extends Dto<MODEL>, MODEL extends Entity<ID>, ID>
        implements InvocationHandler {

    private final Class<DTO> dtoClass;
    private final Class<ID> idClass;
    private final EntityMetadata entityMetadata;
    private final SqlExecutor sqlExecutor;
    private final Dialect dialect;

    @SuppressWarnings("unchecked")
    public RepositoryProxyHandler(Class<? extends Repository<?,?,?>> repositoryInterface, SqlExecutor sqlExecutor, Dialect dialect) {
        var typeInfo = TypeResolver.resolveRepositoryTypes(repositoryInterface);
        this.dtoClass = (Class<DTO>) typeInfo.dtoClass();
        Class<MODEL> modelClass = (Class<MODEL>) typeInfo.modelClass();
        this.idClass = (Class<ID>) typeInfo.idClass();
        this.entityMetadata = EntityMetadataRegistry.getInstance().getMetadata(modelClass);
        this.sqlExecutor = sqlExecutor;
        this.dialect = dialect;
    }

    public RepositoryProxyHandler(Class<DTO> dtoClass, Class<MODEL> modelClass, Class<ID> idClass,
                                  SqlExecutor sqlExecutor, Dialect dialect) {
        this.dtoClass = dtoClass;
        this.idClass = idClass;
        this.entityMetadata = EntityMetadataRegistry.getInstance().getMetadata(modelClass);
        this.sqlExecutor = sqlExecutor;
        this.dialect = dialect;
    }

    @Override
    public Object invoke(Object proxy, Method method, Object[] args) {
        String methodName = method.getName();

        return switch (methodName) {
            case "save" -> save((DTO) args[0]);
            case "findById" -> findById((ID) args[0]);
            case "findAll" -> findAll();
            case "deleteById" -> { deleteById((ID) args[0]); yield null; }
            case "delete" -> { delete((DTO) args[0]); yield null; }
            case "existsById" -> existsById((ID) args[0]);
            case "count" -> count();
            case "saveAll" -> saveAll((Iterable<DTO>) args[0]);
            case "deleteAll" -> {
                if (args.length == 0) deleteAll();
                else deleteAll((Iterable<DTO>) args[0]);
                yield null;
            }
            case "query" -> query();
            default -> {
                if (methodName.startsWith("findBy")) {
                    yield handleDynamicFinderMethod(method, args);
                }
                throw new VictorException("Unsupported repository method: " + methodName);
            }
        };
    }

    private boolean shouldUseSimpleInsert(MODEL model) {
        return entityMetadata.getIdField().isAutoGenerated() && model.isNew();
    }

    private DTO save(DTO dto) {
        try {
            MODEL model = dto.toModel();

            if (shouldUseSimpleInsert(model)) {
                return insert(dto, model);
            } else {
                return upsert(dto, model);
            }

        } catch (Exception e) {
            throw new VictorException("Failed to save entity: " + dto, e);
        }
    }

    private DTO upsert(DTO dto, MODEL model) {
        String sql = dialect.generateUpsert(entityMetadata);
        Object[] params = entityMetadata.getFields().stream()
                .map(field -> field.getValue(model))
                .toArray();

        int rowsAffected = sqlExecutor.executeUpsert(sql, params);
        if (rowsAffected == 0) {
            throw new VictorException("UPSERT failed, no rows affected: " + model.getId());
        }

        return dto;
    }

    private DTO insert(DTO dto, MODEL model) {
        String sql = dialect.generateInsert(entityMetadata);
        Object[] params = extractNonIdFieldValues(model);

        if (entityMetadata.getIdField().isAutoGenerated()) {
            ID generatedId = sqlExecutor.executeInsertWithGeneratedKey(sql, params, idClass);
            model.setId(generatedId);

            return createDtoFromModel(model);
        } else {
            sqlExecutor.executeUpdate(sql, params);
            return dto;
        }
    }

    private DTO update(DTO dto, MODEL model) {
        String sql = dialect.generateUpdate(entityMetadata);
        Object[] params = extractAllFieldValues(model);

        int rowsAffected = sqlExecutor.executeUpdate(sql, params);

        if (rowsAffected == 0) {
            throw new VictorEntityNotFoundException(
                    model.getClass(),
                    model.getId(),
                    "Entity not found for update. Use insert() instead or check if ID exists."
            );
        }

        return dto;
    }

    private Optional<DTO> findById(ID id) {
        String sql = dialect.generateSelectById(entityMetadata);
        Object[] params = { id };

        SqlExecutor.RowMapper<DTO> mapper = DtoMapper.createMapper(dtoClass, entityMetadata, sqlExecutor);
        DTO result = sqlExecutor.executeQuerySingle(sql, params, mapper);

        return Optional.ofNullable(result);
    }

    private List<DTO> findAll() {
        String sql = dialect.generateSelectAll(entityMetadata);
        SqlExecutor.RowMapper<DTO> mapper = DtoMapper.createMapper(dtoClass, entityMetadata, sqlExecutor);
        return sqlExecutor.executeQuery(sql, null, mapper);
    }

    private void deleteById(ID id) {
        String sql = dialect.generateDelete(entityMetadata);
        Object[] params = { id };

        int rowsAffected = sqlExecutor.executeUpdate(sql, params);
        if (rowsAffected == 0) {
            throw new VictorException("Entity not found for deletion: " + id);
        }
    }

    private void delete(DTO dto) {
        MODEL model = dto.toModel();
        if (model.getId() == null) {
            throw new VictorException("Cannot delete entity without ID");
        }
        deleteById(model.getId());
    }

    private boolean existsById(ID id) {
        String sql = dialect.generateExists(entityMetadata);
        Object[] params = { id };

        long count = sqlExecutor.executeCount(sql, params);
        return count > 0;
    }

    private long count() {
        String sql = dialect.generateCount(entityMetadata);
        return sqlExecutor.executeCount(sql, null);
    }

    private List<DTO> saveAll(Iterable<DTO> dtos) {
        return StreamSupport.stream(dtos.spliterator(), false)
                .map(this::save)
                .toList();
    }

    private void deleteAll(Iterable<DTO> dtos) {
        dtos.forEach(this::delete);
    }

    private void deleteAll() {
        String tableName = dialect.quoteIdentifier(entityMetadata.getTableName());
        if (entityMetadata.getSchema() != null) {
            tableName = dialect.quoteIdentifier(entityMetadata.getSchema()) + "." + tableName;
        }
        String sql = "DELETE FROM " + tableName;
        sqlExecutor.executeUpdate(sql, null);
    }

    private Query<DTO> query() {
        return new QueryProxyHandler<>(dtoClass, entityMetadata, sqlExecutor, dialect).createProxy();
    }

    private Object handleDynamicFinderMethod(Method method, Object[] args) {
        // TODO: Parse method name and create appropriate query
        // Examples: findByUsername, findByEmailAndActive, findByAgeGreaterThan
        String methodName = method.getName();

        // For now, return empty results
        if (method.getReturnType() == Optional.class) {
            return Optional.empty();
        } else if (List.class.isAssignableFrom(method.getReturnType())) {
            return List.of();
        } else {
            return null;
        }
    }

    // ========== Helper Methods (inchangés) ==========

    private Object[] extractNonIdFieldValues(MODEL model) {
        return entityMetadata.getNonIdFields().stream()
                .map(field -> field.getValue(model))
                .toArray();
    }

    private Object[] extractAllFieldValues(MODEL model) {
        var nonIdValues = entityMetadata.getNonIdFields().stream()
                .map(field -> field.getValue(model))
                .toList();

        var allValues = new java.util.ArrayList<>(nonIdValues);
        allValues.add(entityMetadata.getIdField().getValue(model));

        return allValues.toArray();
    }

    private DTO createDtoFromModel(MODEL model) {
        try {
            if (dtoClass.isRecord()) {
                return createRecordFromModel(model);
            } else {
                return createClassFromModel(model);
            }
        } catch (Exception e) {
            throw new VictorException("Failed to create DTO from model", e);
        }
    }

    private DTO createRecordFromModel(MODEL model) throws Exception {
        var components = dtoClass.getRecordComponents();
        Object[] args = new Object[components.length];

        for (int i = 0; i < components.length; i++) {
            String componentName = components[i].getName();

            // Find field by name
            FieldMetadata field = findFieldByName(componentName);
            if (field != null) {
                args[i] = field.getValue(model);
            }
        }

        var constructor = dtoClass.getDeclaredConstructor(
                java.util.Arrays.stream(components).map(java.lang.reflect.RecordComponent::getType).toArray(Class[]::new)
        );

        return constructor.newInstance(args);
    }

    private DTO createClassFromModel(MODEL model) throws Exception {
        DTO dto = dtoClass.getDeclaredConstructor().newInstance();

        var fields = dtoClass.getDeclaredFields();
        for (var field : fields) {
            field.setAccessible(true);

            FieldMetadata entityField = findFieldByName(field.getName());
            if (entityField != null) {
                Object value = entityField.getValue(model);
                field.set(dto, value);
            }
        }

        return dto;
    }

    private FieldMetadata findFieldByName(String name) {
        return entityMetadata.getFields().stream()
                .filter(f -> f.getField().getName().equals(name) || f.getColumnName().equals(name))
                .findFirst()
                .orElse(null);
    }

    @SuppressWarnings("unchecked")
    public static <T extends Repository<?,?,?>> T createProxy(Class<T> repositoryInterface, SqlExecutor sqlExecutor, Dialect dialect) {
        var handler = new RepositoryProxyHandler<>(repositoryInterface, sqlExecutor, dialect);
        return (T) Proxy.newProxyInstance(
                repositoryInterface.getClassLoader(),
                new Class[]{repositoryInterface},
                handler
        );
    }
}